name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_on_node:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [15.x, 14.x, 12.x]
        include:
          - os: windows-latest
            node: '12.x'
          - os: macOS-latest
            node: '12.x'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Packages
        run: npm install
      - name: lint
        run: npm run lint
      - name: Test
        run: npm run test
