name: lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_on_node:
    name: lint
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Packages
        run: npm install
      - name: lint
        run: npm run lint
